version: '3.3'
services:
  stable-diffusion:
# uncomment to build from source
#    build:
#      context: ./stable-diffusion-web
#      dockerfile: Dockerfile
    image: ghcr.io/parzival-space/stable-diffusion:latest
    environment:
      - LAUNCH_ARGS=--xformers --update-check --enable-insecure-extension-access
    volumes:
      - ./data/stable-diffusion-web/configs:/data/configs
      - ./data/stable-diffusion-web/embeddings:/data/embeddings
      - ./data/stable-diffusion-web/extensions:/data/extensions
      - ./data/stable-diffusion-web/models:/data/models
      - ./data/stable-diffusion-web/outputs:/data/outputs
      - sd_repositories:/data/repositories # diffuser repositories
      - sd_venv:/data/venv # python venv
    ports:
      - "0.0.0.0:7680:7680"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
volumes:
  sd_venv:
  sd_repositories: