version: '3.3'
services:
  comfy-ui:
    #     uncomment to build from source
    build:
      context: ./comfy-ui
      dockerfile: Dockerfile
    image: ghcr.io/parzival-space/stable-diffusion:comfy-ui
    environment:
      - LAUNCH_ARGS=--preview-method auto
    volumes:
      - ./data/comfy-ui/custom_nodes:/data/custom_nodes
      - ./data/comfy-ui/models:/data/models
      - ./data/comfy-ui/outputs:/data/outputs
      - venv:/data/venv # python venv
      - comfy:/data/comfy-ui # comfy-ui git repository
    ports:
      - "0.0.0.0:8188:8188"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
volumes:
  venv:
  comfy: